### ISSUE TITLE
msperlin/adfeR não está mais disponível?

### ISSUE THREAD

**Issue by andreltr** [msperlin/adfeR#1]
Olá,

O pacote acima não está mais disponível? Eu não consegui baixa-lo no link informado, senão vejamos,

devtools::install_github('msperlin/adfeR')
Downloading GitHub repo msperlin/adfeR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet, :
download from 'https://api.github.com/repos/msperlin/adfeR/tarball/HEAD' failed
devtools::install_github('msperlin/adfeR')
Downloading GitHub repo msperlin/adfeR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet, :
download from 'https://api.github.com/repos/msperlin/adfeR/tarball/HEAD' failed
Desde já agradeço qualquer explicação sobre como resolver essa situação.

Atenciosamente,

--
André Luiz Tietböhl Ramos, Dr.

**Comment by msperlin** [comment]
Oi André,

Testei aqui e funcionou. Podes tentar novamente por favor? Me avisa como foi.

**Comment by andreltr** [comment]
Olá Marcelo,

Tentei novamente e obtive a mesma resposta, abaixo.

> devtools::install_github('msperlin/adfeR')
Downloading GitHub repo msperlin/adfeR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/msperlin/adfeR/tarball/HEAD' failed
> 

Inclusive, anteriormente eu utilizei R a partir do emacs por preferência pessoal. Na segunda vez foi a partir do R Console; ambas tentativas foram no Mac OSX.

Atenciosamente,

--
André Luiz Tietböhl Ramos, Dr.

**Comment by msperlin** [comment]
Nao sei dizer o que está acontecendo, pois o repositorio está online. Talvez tenhas atingido o limite de chamadas ao github. Tenta usar o remotes::install_github() e me diga se faz diferença.

**Comment by andreltr** [comment]
Olá,

Eu já consegui fazer o download e instalar, obrigado. Por alguma razão, que desconheço, eu tive que usar o R Console no MACOSX tal; a interface via ESS r-mode do emacs não funcionou.

Atenciosamente,

--
Andre Luiz Tietbohl Ramos, Dr.

**Comment by msperlin** [comment]
Que engraçado. Mas que bom que foi solucionado.
